apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.16  # Version ancienne et vulnérable
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0  # Root user - mauvaise pratique
          privileged: true  # Mode privilégié - dangereux
        resources: {}  # Pas de limites - problématique
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-service
spec:
  selector:
    app: vulnerable-app
  ports:
  - port: 80
  type: NodePort